security:
  oauth2:
    client:
      client-id: oauth2_client
      client-secret: oauth2_client_secret
      scope: read, write
      auto-approve-scopes: .*
      authorized-grant-types: authorization_code
    authorization:
      check-token-access: permitAll()
server:
  port: 8081
  context-path: /auth
logging:
  level:
    org.springframework.security: DEBUG
client:
  url: http://localhost:8082